// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzWD-aEZpW5W5pnuPW4Iu7IFuqXl1PRE',
    appId: '1:1016658841277:web:0afa23079ea06901d471d4',
    messagingSenderId: '1016658841277',
    projectId: 'fir-5e050',
    authDomain: 'fir-5e050.firebaseapp.com',
    storageBucket: 'fir-5e050.firebasestorage.app',
    measurementId: 'G-NDES4RJX36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXenwFk994h6S4vUp6Somrjs7bzkJz0ok',
    appId: '1:1016658841277:android:fa227c03c2106772d471d4',
    messagingSenderId: '1016658841277',
    projectId: 'fir-5e050',
    storageBucket: 'fir-5e050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8uJ5MfH51paKb12N1fBoLHSzbnwFdXM',
    appId: '1:1016658841277:ios:eced27fae6df2db4d471d4',
    messagingSenderId: '1016658841277',
    projectId: 'fir-5e050',
    storageBucket: 'fir-5e050.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );
}
